name: Build and Run

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  schedule:
    # 10:45 PM UTC every Sunday
    - cron:  '45 22 * * 0'
jobs:
  build-run:
    name: Build and run with startup msg verification
    uses: jphickey/cFS/.github/workflows/build-run-app-reusable.yml@fix-998-workflow-config
    with:
      eds-enabled: true